SEED_TRANSACTIONS: list[dict] = [
    # ── Groceries ──────────────────────────────────────────────
    {"description": "Lidl", "counterparty": "LIDL", "amount": -45.99, "category_slug": "groceries"},
    {"description": "Biedronka", "counterparty": "BIEDRONKA", "amount": -32.50, "category_slug": "groceries"},
    {"description": "Carrefour", "counterparty": "CARREFOUR", "amount": -88.20, "category_slug": "groceries"},
    {"description": "Auchan", "counterparty": "AUCHAN", "amount": -120.00, "category_slug": "groceries"},
    {"description": "Tesco", "counterparty": "TESCO", "amount": -27.30, "category_slug": "groceries"},
    {"description": "Aldi", "counterparty": "ALDI", "amount": -55.00, "category_slug": "groceries"},
    {"description": "Kaufland", "counterparty": "KAUFLAND", "amount": -92.40, "category_slug": "groceries"},
    {"description": "Zabka", "counterparty": "ZABKA", "amount": -8.50, "category_slug": "groceries"},
    {"description": "Zabka", "counterparty": "ZABKA POLSKA", "amount": -15.00, "category_slug": "groceries"},
    {"description": "Supermarket", "counterparty": "LEWITAT", "amount": -63.00, "category_slug": "groceries"},
    {"description": "Delikatesy", "counterparty": "DELIKATESY CENTRUM", "amount": -41.00, "category_slug": "groceries"},
    {"description": "Piekarnia", "counterparty": "", "amount": -6.50, "category_slug": "groceries"},
    # ── Dining Out ────────────────────────────────────────────
    {"description": "Restauracja Warszawa", "counterparty": "RESTAURACJA U DOMINIKA", "amount": -120.00, "category_slug": "dining"},
    {"description": "Pizza Hut", "counterparty": "PIZZA HUT", "amount": -45.00, "category_slug": "dining"},
    {"description": "McDonald's", "counterparty": "MCDONALD'S", "amount": -25.50, "category_slug": "dining"},
    {"description": "KFC", "counterparty": "KFC", "amount": -32.00, "category_slug": "dining"},
    {"description": "Burger King", "counterparty": "BURGER KING", "amount": -28.00, "category_slug": "dining"},
    {"description": "Starbucks", "counterparty": "STARBUCKS", "amount": -15.00, "category_slug": "dining"},
    {"description": "Costa Coffee", "counterparty": "COSTA COFFEE", "amount": -12.50, "category_slug": "dining"},
    {"description": "Sushi", "counterparty": "SUSHI HOUSE", "amount": -65.00, "category_slug": "dining"},
    {"description": "Kawiarnia", "counterparty": "KAWIARNIA LUKULLUS", "amount": -18.00, "category_slug": "dining"},
    {"description": "Bar", "counterparty": "BAR MLECZNY", "amount": -22.00, "category_slug": "dining"},
    {"description": "Bistro", "counterparty": "BISTRO", "amount": -35.00, "category_slug": "dining"},
    # ── Transport ─────────────────────────────────────────────
    {"description": "PKP", "counterparty": "PKP INTERCITY", "amount": -150.00, "category_slug": "transport"},
    {"description": "PKS", "counterparty": "PKS", "amount": -25.00, "category_slug": "transport"},
    {"description": "Uber", "counterparty": "UBER", "amount": -22.00, "category_slug": "transport"},
    {"description": "Bolt", "counterparty": "BOLT", "amount": -18.50, "category_slug": "transport"},
    {"description": "Taxi", "counterparty": "TAXI", "amount": -35.00, "category_slug": "transport"},
    {"description": "Orlen", "counterparty": "ORLEN", "amount": -200.00, "category_slug": "transport"},
    {"description": "BP", "counterparty": "BP", "amount": -180.00, "category_slug": "transport"},
    {"description": "Shell", "counterparty": "SHELL", "amount": -195.00, "category_slug": "transport"},
    {"description": "Stacja paliw", "counterparty": "CIRCLE K", "amount": -170.00, "category_slug": "transport"},
    {"description": "Bilety komunikacji", "counterparty": "ZTM", "amount": -80.00, "category_slug": "transport"},
    {"description": "Parking", "counterparty": "PARKING", "amount": -8.00, "category_slug": "transport"},
    {"description": "Autostrada", "counterparty": "A4 KATOWICE", "amount": -28.00, "category_slug": "transport"},
    # ── Income / Salary ───────────────────────────────────────
    {"description": "Wynagrodzenie", "counterparty": "EMPLOYER SP ZOO", "amount": 6500.00, "category_slug": "income"},
    {"description": "Salary", "counterparty": "ACME CORP", "amount": 5000.00, "category_slug": "income"},
    {"description": "Przelew wynagrodzenia", "counterparty": "FIRMA", "amount": 7200.00, "category_slug": "income"},
    {"description": "Pensja", "counterparty": "PRACODAWCA", "amount": 4800.00, "category_slug": "income"},
    {"description": "Umowa zlecenie", "counterparty": "ZLECENIODAWCA", "amount": 3000.00, "category_slug": "income"},
    {"description": "Freelance", "counterparty": "UPWORK", "amount": 2500.00, "category_slug": "income"},
    {"description": "Kontrakt", "counterparty": "B2B CONTRACTOR", "amount": 12000.00, "category_slug": "income"},
    {"description": "Zasiłek", "counterparty": "ZUS", "amount": 1500.00, "category_slug": "income"},
    {"description": "Dywidenda", "counterparty": "BROKER", "amount": 800.00, "category_slug": "income"},
    {"description": "Zwrot podatku", "counterparty": "US", "amount": 2000.00, "category_slug": "income"},
    # ── Housing / Rent ────────────────────────────────────────
    {"description": "Czynsz", "counterparty": "WSPOLNOTA MIESZKANIOWA", "amount": -800.00, "category_slug": "housing"},
    {"description": "Rent", "counterparty": "LANDLORD", "amount": -2500.00, "category_slug": "housing"},
    {"description": "Wynajem mieszkania", "counterparty": "WYNAJEMCA", "amount": -3000.00, "category_slug": "housing"},
    {"description": "Opłata administracyjna", "counterparty": "ADMIN", "amount": -200.00, "category_slug": "housing"},
    {"description": "Fundusz remontowy", "counterparty": "WSPOLNOTA", "amount": -150.00, "category_slug": "housing"},
    # ── Utilities ─────────────────────────────────────────────
    {"description": "Tauron", "counterparty": "TAURON", "amount": -180.00, "category_slug": "utilities"},
    {"description": "PGE", "counterparty": "PGE", "amount": -220.00, "category_slug": "utilities"},
    {"description": "Energa", "counterparty": "ENERGA", "amount": -170.00, "category_slug": "utilities"},
    {"description": "Orange", "counterparty": "ORANGE", "amount": -80.00, "category_slug": "utilities"},
    {"description": "Play", "counterparty": "PLAY", "amount": -50.00, "category_slug": "utilities"},
    {"description": "Plus", "counterparty": "PLUS", "amount": -45.00, "category_slug": "utilities"},
    {"description": "T-Mobile", "counterparty": "T-MOBILE", "amount": -60.00, "category_slug": "utilities"},
    {"description": "Vodafone", "counterparty": "VODAFONE", "amount": -55.00, "category_slug": "utilities"},
    {"description": "Internet", "counterparty": "ISP", "amount": -70.00, "category_slug": "utilities"},
    {"description": "Gaz", "counterparty": "PSG", "amount": -120.00, "category_slug": "utilities"},
    {"description": "Woda", "counterparty": "MPWiK", "amount": -65.00, "category_slug": "utilities"},
    {"description": "Wywóz śmieci", "counterparty": "MPO", "amount": -35.00, "category_slug": "utilities"},
    # ── Healthcare ────────────────────────────────────────────
    {"description": "Apteka", "counterparty": "APTEKA", "amount": -45.00, "category_slug": "healthcare"},
    {"description": "Apteka", "counterparty": "DOZ", "amount": -32.00, "category_slug": "healthcare"},
    {"description": "Lekarz", "counterparty": "PRZYCHODNIA", "amount": -150.00, "category_slug": "healthcare"},
    {"description": "Wizyta", "counterparty": "SPECJALISTA", "amount": -200.00, "category_slug": "healthcare"},
    {"description": "Szpital", "counterparty": "SZPITAL", "amount": -300.00, "category_slug": "healthcare"},
    {"description": "Dentysta", "counterparty": "GABINET STOMATOLOGICZNY", "amount": -250.00, "category_slug": "healthcare"},
    {"description": "Badania", "counterparty": "DIAGNOSTYKA", "amount": -100.00, "category_slug": "healthcare"},
    {"description": "Rehabilitacja", "counterparty": "REHABILITACJA", "amount": -120.00, "category_slug": "healthcare"},
    {"description": "Okulista", "counterparty": "KOREKTA", "amount": -180.00, "category_slug": "healthcare"},
    {"description": "Ubezpieczenie zdrowotne", "counterparty": "NATIONAL HEALTH", "amount": -400.00, "category_slug": "healthcare"},
    # ── Shopping ──────────────────────────────────────────────
    {"description": "Allegro", "counterparty": "ALLEGRO", "amount": -150.00, "category_slug": "shopping"},
    {"description": "Amazon", "counterparty": "AMAZON", "amount": -200.00, "category_slug": "shopping"},
    {"description": "Zalando", "counterparty": "ZALANDO", "amount": -180.00, "category_slug": "shopping"},
    {"description": "MediaMarkt", "counterparty": "MEDIAMARKT", "amount": -599.00, "category_slug": "shopping"},
    {"description": "RTV Euro AGD", "counterparty": "RTV EURO AGD", "amount": -450.00, "category_slug": "shopping"},
    {"description": "IKEA", "counterparty": "IKEA", "amount": -350.00, "category_slug": "shopping"},
    {"description": "Decathlon", "counterparty": "DECATHLON", "amount": -120.00, "category_slug": "shopping"},
    {"description": "H&M", "counterparty": "H&M", "amount": -85.00, "category_slug": "shopping"},
    {"description": "Reserved", "counterparty": "RESERVED", "amount": -160.00, "category_slug": "shopping"},
    {"description": "Empik", "counterparty": "EMPIK", "amount": -55.00, "category_slug": "shopping"},
    # ── Entertainment ─────────────────────────────────────────
    {"description": "Netflix", "counterparty": "NETFLIX", "amount": -55.00, "category_slug": "entertainment"},
    {"description": "Spotify", "counterparty": "SPOTIFY", "amount": -20.00, "category_slug": "entertainment"},
    {"description": "HBO Max", "counterparty": "HBO", "amount": -30.00, "category_slug": "entertainment"},
    {"description": "Disney+", "counterparty": "DISNEYPLUS", "amount": -28.99, "category_slug": "entertainment"},
    {"description": "Cinema City", "counterparty": "CINEMA CITY", "amount": -45.00, "category_slug": "entertainment"},
    {"description": "Kino", "counterparty": "KINO", "amount": -32.00, "category_slug": "entertainment"},
    {"description": "Teatr", "counterparty": "TEATR", "amount": -80.00, "category_slug": "entertainment"},
    {"description": "Koncert", "counterparty": "TICKETMASTER", "amount": -150.00, "category_slug": "entertainment"},
    {"description": "Siłownia", "counterparty": "FITNESS CLUB", "amount": -120.00, "category_slug": "entertainment"},
    {"description": "Basen", "counterparty": "BASEN", "amount": -25.00, "category_slug": "entertainment"},
    # ── Education ─────────────────────────────────────────────
    {"description": "Coursera", "counterparty": "COURSERA", "amount": -200.00, "category_slug": "education"},
    {"description": "Udemy", "counterparty": "UDEMY", "amount": -45.00, "category_slug": "education"},
    {"description": "Szkolenie", "counterparty": "TRAINING CENTER", "amount": -500.00, "category_slug": "education"},
    {"description": "Kurs", "counterparty": "JEZYKOWY", "amount": -350.00, "category_slug": "education"},
    {"description": "Studia", "counterparty": "UNIVERSITY", "amount": -1000.00, "category_slug": "education"},
    {"description": "Podręcznik", "counterparty": "PUBLICAT", "amount": -120.00, "category_slug": "education"},
    # ── Transfer / Internal ───────────────────────────────────
    {"description": "Przelew własny", "counterparty": "", "amount": -500.00, "category_slug": "transfer"},
    {"description": "Transfer", "counterparty": "", "amount": 1000.00, "category_slug": "transfer"},
    {"description": "Przelew między rachunkami", "counterparty": "", "amount": -200.00, "category_slug": "transfer"},
    {"description": "Wpłata gotówki", "counterparty": "BANKOMAT", "amount": -2000.00, "category_slug": "transfer"},
    {"description": "Wypłata z bankomatu", "counterparty": "BANK", "amount": -500.00, "category_slug": "transfer"},
]


CATEGORY_SEED_DATA: list[dict] = [
    # (slug, name, icon, parent_slug)
    {"slug": "income", "name": "Income", "icon": "trending-up", "parent_slug": None},
    {"slug": "housing", "name": "Housing", "icon": "home", "parent_slug": None},
    {"slug": "transport", "name": "Transport", "icon": "car", "parent_slug": None},
    {"slug": "groceries", "name": "Groceries", "icon": "shopping-cart", "parent_slug": None},
    {"slug": "dining", "name": "Dining Out", "icon": "coffee", "parent_slug": None},
    {"slug": "utilities", "name": "Utilities", "icon": "zap", "parent_slug": None},
    {"slug": "healthcare", "name": "Healthcare", "icon": "heart", "parent_slug": None},
    {"slug": "entertainment", "name": "Entertainment", "icon": "film", "parent_slug": None},
    {"slug": "shopping", "name": "Shopping", "icon": "package", "parent_slug": None},
    {"slug": "education", "name": "Education", "icon": "book", "parent_slug": None},
    {"slug": "transfer", "name": "Transfer", "icon": "arrow-left-right", "parent_slug": None},
    {"slug": "other", "name": "Other", "icon": "more-horizontal", "parent_slug": None},
]
