"""create holding table for portfolio tracking

Revision ID: a1b2c3d4e5f6
Revises: be8fd5d5b9e7
Create Date: 2026-07-01 12:00:00.000000

Sprint 2 — portfolio feature: a `holding` table that lets users
track investment holdings (stocks, ETFs, crypto, etc.) manually.
Linked to `account` via an optional FK so investment accounts
discovered via open-banking sync can later feed into portfolio
aggregation without a schema change.

Cascade spine (same constraint as data-layer migration):
    users -> bank_connection -> account -> transaction   (all CASCADE)
    users -> category                                      (CASCADE)
    users -> budget                                        (CASCADE)
    users -> holding                                       (CASCADE)

`holding.account_id` is NO ACTION — deleting an account leaves
its manual holdings intact (user may want to keep tracking them
after unlinking the bank).

Constraints/indexes are explicitly named to match this project's
naming convention (`pk_<table>`, `fk_<table>_<col>_<ref_table>`,
`ix_<table>_<col>`), consistent with every other hand-authored
migration here — `op.create_table` does not apply the model
metadata's naming convention on its own, so leaving names unset
would let SQL Server assign non-deterministic autogenerated ones
(e.g. `PK__holding__...`).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "be8fd5d5b9e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "holding",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("account_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("symbol", sa.Unicode(length=20), nullable=False),
        sa.Column("name", sa.Unicode(length=255), nullable=False),
        sa.Column(
            "asset_type",
            sa.String(length=20),
            nullable=False,
            server_default="other",
        ),
        sa.Column("currency", sa.Unicode(length=3), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=19, scale=8), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=19, scale=6), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Unicode(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_holding"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_holding_user_id_users",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["account.id"], name="fk_holding_account_id_account"
        ),
    )
    op.create_index("ix_holding_user_id", "holding", ["user_id"])
    op.create_index("ix_holding_account_id", "holding", ["account_id"])
    op.create_index("ix_holding_symbol", "holding", ["symbol"])


def downgrade() -> None:
    # NOTE: asset_type is stored as a plain VARCHAR (native_enum=False
    # on the model's Enum column, i.e. no CHECK constraint or SQL
    # Server type is created for it) — there is nothing beyond the
    # table itself to drop. An earlier draft of this migration ran
    # `DROP TYPE asset_type` here, which would have failed against
    # real MSSQL since no such type object exists for a native_enum=False
    # column; SQL Server has no user-defined enum type at all.
    op.drop_index("ix_holding_symbol", table_name="holding")
    op.drop_index("ix_holding_account_id", table_name="holding")
    op.drop_index("ix_holding_user_id", table_name="holding")
    op.drop_table("holding")
